---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-twistedsolutions-se-v1alpha1-fqdnnetworkpolicy
  failurePolicy: Fail
  name: mfqdnnetworkpolicy.kb.io
  rules:
  - apiGroups:
    - twistedsolutions.se
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fqdnnetworkpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-twistedsolutions-se-v1alpha1-fqdnnetworkpolicy
  failurePolicy: Fail
  name: vfqdnnetworkpolicy.kb.io
  rules:
  - apiGroups:
    - twistedsolutions.se
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fqdnnetworkpolicies
  sideEffects: None
