# permissions for end users to view fqdnnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fqdnnetworkpolicy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fqdn-operator
    app.kubernetes.io/part-of: fqdn-operator
    app.kubernetes.io/managed-by: kustomize
  name: fqdnnetworkpolicy-viewer-role
rules:
- apiGroups:
  - networking.twistedsolutions.se
  resources:
  - fqdnnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.twistedsolutions.se
  resources:
  - fqdnnetworkpolicies/status
  verbs:
  - get
