---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicy
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicy/finalizers
  verbs:
  - update
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicy/status
  verbs:
  - get
  - patch
  - update
