---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicies/status
  verbs:
  - get
  - patch
  - update
