apiVersion: twistedsolutions.se/v1alpha1
kind: FqdnNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/name: fqdnnetworkpolicy
    app.kubernetes.io/instance: fqdnnetworkpolicy-sample
    app.kubernetes.io/part-of: fqdn-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: fqdn-operator
  name: fqdnnetworkpolicy-sample
spec:
  # TODO(user): Add fields here
