name: Build Image on Tag

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: fqdn-operator
        tags: latest ${{ env.RELEASE_VERSION }}
        containerfiles: |
          ./Dockerfile