name: Build Image on PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: fqdn-operator
        tags: latest $GITHUB_BASE_REF
        containerfiles: |
          ./Dockerfile