name: Build Image on push

on:
  push:
    branches:
      - dev
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: fqdn-operator
        tags: latest ${{ github.ref_name }}
        containerfiles: |
          ./Dockerfile
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/twistedsolutions
        username: twistedsolutions+github
        password: ${{ secrets.REGISTRY_PASSWORD }}