name: Build Image on push

on:
  push:
    branches:
      - dev
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: fqdn-operator
        tags: latest ${{ github.base_ref }}
        containerfiles: |
          ./Dockerfile