name: Run Tests

on: [push, pull_request]

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
    - uses: actions/checkout@v4
    - run: go mod tidy && git diff --exit-code go.mod go.sum
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21.6
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run go vet
      run: go vet ./...
    - name: Setup test env
      run: make envtest
    - name: Run tests
      run: make test